export const CONSTANTS = {
  STREAMS: {
    GET_STREAMS: "GET_STREAMS",
    GET_STEP_TYPE: "GET_STEP_TYPE",
    GET_STREAM_PROCESSORS: "GET_STREAM_PROCESSORS",
    GET_SIMULATIONS: "GET_SIMULATIONS",
    ADD_NEW_STEP: "ADD_NEW_STEP",
    DELL_NEW_STEP: "DELL_NEW_STEP",
  },
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_CONFIG: "GET_CONFIG",
};
